//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int AlbumId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Title { get; set; }
        public string Alt { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
