//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int ProductId { get; set; }
        public string Microprocessor { get; set; }
        public Nullable<double> Speed { get; set; }
        public string Graphics { get; set; }
        public string RAM { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Hardware { get; set; }
        public string Monitor { get; set; }
        public Nullable<double> Monitorsize { get; set; }
        public string Operation { get; set; }
        public string Color { get; set; }
        public string Connection { get; set; }
        public string Gate { get; set; }
        public Nullable<bool> Webcam { get; set; }
        public Nullable<bool> Recognition { get; set; }
        public string Battery { get; set; }
        public string Size { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Description { get; set; }
        public string Core { get; set; }
        public string Disc { get; set; }
    }
}
