//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int ProductId { get; set; }
        public int OriginalStockQuantity { get; set; }
        public int StockQuantity { get; set; }
        public bool StockStatus { get; set; }
    }
}
