//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricStore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectricStore.Properties.ProductResources", typeof(ProductResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới chi tiết sản phẩm không thành công.
        /// </summary>
        internal static string CREATE_PRODUCT_DETAIL_FAILURE {
            get {
                return ResourceManager.GetString("CREATE_PRODUCT_DETAIL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới chi tiết sản phẩm {0} thành công.
        /// </summary>
        internal static string CREATE_PRODUCT_DETAIL_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_PRODUCT_DETAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới sản phẩm thất bại.
        /// </summary>
        internal static string CREATE_PRODUCT_FAILURE {
            get {
                return ResourceManager.GetString("CREATE_PRODUCT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới sản phẩm thành công.
        /// </summary>
        internal static string CREATE_PRODUCT_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_PRODUCT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa sản phẩm không thành công.
        /// </summary>
        internal static string DELETE_PRODUCT_FAILURE {
            get {
                return ResourceManager.GetString("DELETE_PRODUCT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa sản phẩm thành công.
        /// </summary>
        internal static string DELETE_PRODUCT_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_PRODUCT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi chi tiết sản phẩm không thành công.
        /// </summary>
        internal static string UPDATE_PRODUCT_DETAIL_FAILURE {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_DETAIL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi chi tiết sản phẩm thành công.
        /// </summary>
        internal static string UPDATE_PRODUCT_DETAIL_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_DETAIL_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thông tin sản phẩm không thành công.
        /// </summary>
        internal static string UPDATE_PRODUCT_FAILURE {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thông tin sản phẩm thành công.
        /// </summary>
        internal static string UPDATE_PRODUCT_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PRODUCT_SUCCESS", resourceCulture);
            }
        }
    }
}
